## Note, "[ci skio]" or "[skip ci]" within a commit message _should_
##  cause Travis Continuous Integration to skip the following


## Clone settings for repository
##   1. Reduce log _fluff_ with `true`
##   2. Clone submodules when cloning this branch with `true`
##   3. Clone the whole Git history with `false`, or set integer limit
git:
  quite: false
  submodules: false
  depth: false


## The dialect that will be spoken
##   1. Really what Jest speeks
##   2. Version of `node_js` to target
language: node_js
node_js:
  - '16'


## Things to keep between CI runs
##   keep `node_modules` subdirectory to speed up future tests, maybe?
cache:
  directories:
    - node_modules


## Operating systems to spin-up
##   1. When `true` some blocks such as `script` terminates at first failure
##   2. List of OS configurations Travis should test with
matrix:
  fast_finish: true
  include:
    ## Default 'dist' was 'trusty' as of 2019
    - name: 'Linux Xenial'
      os: linux
      dist: xenial


## Restrict what branches are cloned with Git
##   1. Fetch `only` `main` or _`test-`_ prefixed branches
##   2. Specifically ignore fetching the `gh-pages` branch
branches:
  only:
    - main
    - /^(?i:test)-.*$/
  except:
    - gh-pages


## Install deps and run CI tests under `test` directory
##   Note, `npm ci` takes the place of `npm install` to ensure
##   all dependencies are installed, and that there are no sync
##   bugs between `package.json` and `package-lock.json` files.
before_install:
  - npm set-script prepare ''
  - npm update
install:
  - npm ci
script:
  - npm run ganache-cli 1>/dev/null &
  - sleep 5
  - npm test

